# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
pipelines:
  default:
    - step:
        image: tfirdaus/wp-docklines:php7.1-fpm-alpine
        name: "PHP 7.1"
        script:
          ## Run PHPUnit
          - bash bin/install-wp-tests.sh wordpress_tests wp password 127.0.0.1 latest true
          - phpunit
        services:
          - database
definitions:
  services:
    database:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: 'wordpress_tests'
        MYSQL_USER: 'wp'
        MYSQL_PASSWORD: 'password'