# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
pipelines:
  default:
    - step:
        image: tfirdaus/wp-docklines:php5.6-fpm-alpine
        name: "PHP 5.6"
        script:
          ## Run PHPCS
          - vendor/bin/phpcs
          ## Run PHPUnit
          - bash bin/install-wp-tests.sh wordpress_tests root root 127.0.0.1 latest true
          - phpunit
        services:
          - database
    - step:
        image: tfirdaus/wp-docklines:php7.2-fpm-alpine
        name: "PHP 7.2"
        script:
          ## Run PHPCS
          - vendor/bin/phpcs
          ## Run PHPUnit
          - bash bin/install-wp-tests.sh wordpress_tests root root 127.0.0.1 latest true
          - phpunit
        services:
          - database

definitions:
  services:
    database:
      image: mysql:latest
      environment:
        MYSQL_DATABASE: "wordpress_tests"
        MYSQL_ROOT_PASSWORD: "root"
