# This is a sample build configuration for PHP.
# Check our guides at https://confluence.atlassian.com/x/e8YWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: php:7.1.29

pipelines:
  default:
    - step:
        caches:
          - composer
        services: 
          - mysql
        script:
          - apt-get update && apt-get install -y unzip
          - pear -V
          - pear install pear/PHP_CodeSniffer
          - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
          - curl -O https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
          - chmod +x wp-cli.phar
          - mv wp-cli.phar /usr/local/bin/wp
          - bin/install-wp-tests.sh wordpress_test root '' localhost latest
          - composer require phpunit/phpunit
          - vendor/bin/phpunit
definitions: 
  services: 
    mysql: 
      image: mysql:5.7
      variables:
        MYSQL_DATABASE: 'pipelines'
        MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
        MYSQL_USER: 'test_user'
        MYSQL_PASSWORD: 'test_user_password'
